# Generated by Django 5.0.7 on 2024-10-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_student_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rating', models.IntegerField()),
                ('year', models.IntegerField(null=True)),
                ('budget', models.IntegerField(default=1000000)),
                ('slug', models.SlugField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
